import { useEffect, useState } from 'react';
import { fetchPlans, request } from '../services/api';
import Page, { Notice } from './Page';
const localDate=value=>{const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export default function AdminLiveClasses(){
 const [classes,setClasses]=useState([]),[plans,setPlans]=useState([]),[editing,setEditing]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError('');try{const [rows,options]=await Promise.all([request('/classes'),fetchPlans()]);setClasses(rows);setPlans(options);}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 async function save(event){event.preventDefault();if(busy)return;const form=event.currentTarget,f=new FormData(form),v=Object.fromEntries(f);setBusy(true);setError('');setMessage('');try{if(new Date(v.end_date)<=new Date(v.class_date))throw new Error('End must be after start.');const plan_ids=f.getAll('plan_ids').map(Number);if(!plan_ids.length)throw new Error('Select at least one plan.');await request('/classes'+(editing?'/'+editing.id:''),{method:editing?'PUT':'POST',body:{name:v.name.trim(),url:v.url,class_date:new Date(v.class_date).toISOString(),end_date:new Date(v.end_date).toISOString(),end_time:v.end_date.slice(11),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,is_active:v.is_active==='on',plan_ids}});setEditing(null);form.reset();await load();setMessage('Class saved successfully.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <Page title="Manage live classes">{error&&<Notice error>{error} <button onClick={load}>Reload</button></Notice>}{message&&<Notice>{message}</Notice>}{loading&&<Notice>Loading classes...</Notice>}<form key={editing?.id||'new'} onSubmit={save} className="bg-white p-6"><h2 className="text-2xl font-bold">{editing?'Edit class':'Create class'}</h2><p className="my-4">Enter times in your local timezone: {Intl.DateTimeFormat().resolvedOptions().timeZone}</p><fieldset disabled={busy||loading} className="grid gap-5 md:grid-cols-2">{[['name','Name','text'],['url','Meeting URL','url'],['class_date','Start','datetime-local'],['end_date','End','datetime-local']].map(([name,label,type])=><label key={name}>{label}<input className="form-input" name={name} type={type} defaultValue={editing?.[name]?type==='datetime-local'?localDate(editing[name]):editing[name]:''} required/></label>)}<label><input type="checkbox" name="is_active" defaultChecked={editing?editing.is_active:true}/> Active</label><fieldset><legend className="font-bold">Eligible plans</legend>{plans.map(p=><label key={p.id} className="mr-4 inline-block"><input type="checkbox" name="plan_ids" value={p.id} defaultChecked={editing?.plan_ids?.includes(p.id)}/> {p.name}</label>)}</fieldset><button className="btn">{busy?'Saving...':'Save class'}</button>{editing&&<button type="button" onClick={()=>setEditing(null)}>Cancel edit</button>}</fieldset></form><div className="mt-8 grid gap-4">{!loading&&!classes.length&&<Notice>No classes yet.</Notice>}{classes.map(row=><article key={row.id} className="flex flex-wrap items-center justify-between gap-4 border border-ink/15 bg-white p-5"><div><h2 className="font-bold">{row.name}</h2><p>{new Date(row.class_date).toLocaleString()} ? {new Date(row.end_date).toLocaleString()}</p><p>{row.is_active?'Active':'Inactive'} ? {row.timezone}</p></div><button className="btn" disabled={busy} onClick={()=>{setEditing(row);window.scrollTo({top:0,behavior:'smooth'});}}>Edit</button></article>)}</div></Page>;
}
